name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Go mod package
        run: |
          go get -v -t -d ./...

      - name: Go Build
        run: |
          go build -v ./...

      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v2